# Pre-commit hook configuration
# Auto-stages only fixed files, not all changes
default_stages: [pre-commit]
default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
    -   id: ruff
        args: [--fix]
        exclude: ^claude-dev-log-diary/
    -   id: ruff-format
        exclude: ^claude-dev-log-diary/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies:
        -   types-pyyaml
        -   types-requests
        exclude: ^(claude-dev-log-diary/|specs/)
