repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^claude-dev-log-diary/
    -   id: end-of-file-fixer
        exclude: ^claude-dev-log-diary/
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        args: [--line-length=88]
        exclude: ^claude-dev-log-diary/

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        args: ['--max-line-length=88', '--extend-ignore=E203']
        exclude: ^claude-dev-log-diary/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies:
        -   types-pyyaml
        -   types-requests
        exclude: ^claude-dev-log-diary/
