name: Archive Claude Code Logs

# DISABLED: Workflow causes commit churn in main branch
# TODO: Implement orphan branch approach or use GitHub Artifacts
# on:
#   workflow_run:
#     workflows: ["Claude Code"]
#     types: [completed]
#   workflow_dispatch:
#     inputs:
#       run_id:
#         description: 'Specific run ID to archive (optional)'
#         required: false
#         type: string

# Temporary: Keep workflow from running
on:
  workflow_dispatch:
    inputs:
      disabled:
        description: 'This workflow is currently disabled'
        required: false
        type: string

jobs:
  archive-logs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for main branch
      
      - name: Setup orphan branch for logs
        run: |
          # Check if claude-logs orphan branch exists
          if git ls-remote --heads origin claude-logs | grep -q claude-logs; then
            echo "Fetching existing claude-logs branch..."
            git fetch origin claude-logs:claude-logs
            git worktree add -B claude-logs logs-worktree origin/claude-logs
          else
            echo "Creating new orphan branch claude-logs..."
            git worktree add --detach logs-worktree
            cd logs-worktree
            git checkout --orphan claude-logs
            git rm -rf . 2>/dev/null || true
            echo "# Claude Code Workflow Logs Archive" > README.md
            echo "" >> README.md
            echo "This orphan branch contains archived Claude Code workflow logs." >> README.md
            echo "Files are managed by the archive-claude-logs.yml workflow." >> README.md
            git add README.md
            git commit -m "initial: create orphan branch for Claude logs"
            cd ..
          fi
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Configure git
        run: |
          git config --global user.name "Claude Log Archiver[bot]"
          git config --global user.email "claude-log-archiver@anthropic.com"
      
      - name: Archive workflow logs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Copy the fetch script to logs worktree
          cp claude-dev-log-diary/fetch_logs.py logs-worktree/
          cd logs-worktree
          
          if [ "${{ github.event.inputs.run_id }}" != "" ]; then
            echo "Archiving specific run ID: ${{ github.event.inputs.run_id }}"
            python fetch_logs.py --run-id ${{ github.event.inputs.run_id }}
          else
            echo "Archiving recent Claude Code workflow runs..."
            python fetch_logs.py --limit 10
          fi
          
          # Clean up the copied script
          rm fetch_logs.py
      
      - name: Commit archived logs to orphan branch
        run: |
          cd logs-worktree
          
          # Stage any new files in github/ directory
          if [ -d github ]; then
            git add github/
          fi
          
          if git diff --staged --quiet; then
            echo "No new logs to archive"
          else
            # Count new files
            new_files=$(git diff --staged --name-status | grep '^A' | wc -l | tr -d ' ')
            
            git commit -m "archive: preserve Claude Code workflow logs
            
            Added $new_files new log file(s) from recent workflow runs.
            
            🤖 Generated by Claude Log Archiver"
            
            git push origin claude-logs
            echo "Archived $new_files log(s) to claude-logs branch"
          fi
          
          # Clean up worktree
          cd ..
          git worktree remove logs-worktree